config/routes.rb
Rails.application.routes.draw do
 
  get 'hello_world', to: 'hello_world#index'
  resources :clientes do
  	resources :criancas
  	resources :telefones
  	resources :emails
 	get :search, :action => 'search', :as => 'search'
  end
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	has_many :criancas, dependent: :destroy
	has_many :telefones, dependent: :destroy
	has_many :emails, dependent: :destroy
	validates :name, presence: true,
					length: {minimum: 5}


	def change
		create_table :clientes do |t|
			t.string :name
			t.text :address
			t.timestamps
		end
	end

	def self.search(search)
		if search
			self.where("name LIKE ?", "%#{search}%")
		else
			self.all
		end
	end

end

app/models/crianca.rb
class Crianca < ApplicationRecord
  belongs_to :cliente
  
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :cliente
end

app/models/telefone.rb
class Telefone < ApplicationRecord
  belongs_to :cliente
	validates :ddd, presence: true,
					length: {minimum: 2, maximum: 3}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
	def index
		@clientes = Cliente.all
		if params[:search]
			@clientes = Cliente.search(params[:search])
		else
			@clientes = Cliente.all
		end
	end

	def show
		@cliente = Cliente.find(params[:id])
	end

	def new
		@cliente = Cliente.new
		render 'new'
	end

	def edit
		@cliente = Cliente.find(params[:id])
	end

	def create
		@cliente = Cliente.new(cliente_params)

		if @cliente.save
			redirect_to @cliente
		else
			render 'new'
		end
	end

	def update
		@cliente = Cliente.find(params[:id])

		if @cliente.update(cliente_params)
			redirect_to @cliente
		else
			render 'edit'
		end
	end

	def destroy
		@cliente = Cliente.find(params[:id])
		@cliente.destroy

		redirect_to clientes_path
	end

	private
	def cliente_params
		params.require(:cliente).permit(:name, :address)
	end
end

app/controllers/criancas_controller.rb
class CriancasController < ApplicationController
	def create
		@cliente = Cliente.find(params[:cliente_id])
		@crianca = @cliente.criancas.create(crianca_params)
		redirect_to cliente_path(@cliente)
	end

	def destroy
		@cliente = Cliente.find(params[:cliente_id])
		@crianca = @cliente.criancas.find(params[:id])
		@crianca.destroy
		redirect_to cliente_path(@cliente)
	end

	private
	def crianca_params
		params.require(:crianca).permit(:name, :mes, :ano)
	end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
	def create
		@cliente = Cliente.find(params[:cliente_id])
		@email = @cliente.emails.create(email_params)
		redirect_to cliente_path(@cliente)
	end

	def destroy
		@cliente = Cliente.find(params[:cliente_id])
		@email = @cliente.emails.find(params[:id])
		@email.destroy
		redirect_to cliente_path(@cliente)
	end

	private
	def email_params
		params.require(:email).permit(:address)
	end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/telefones_controller.rb
class TelefonesController < ApplicationController
	def create
		@cliente = Cliente.find(params[:cliente_id])
		@telefone = @cliente.telefones.create(fone_params)
		redirect_to cliente_path(@cliente)
	end

	def destroy
		@cliente = Cliente.find(params[:cliente_id])
		@telefone = @cliente.telefones.find(params[:id])
		@telefone.destroy
		redirect_to cliente_path(@cliente)
	end

	private
	def fone_params
		params.require(:telefone).permit(:ddd, :fone, :tipo)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criancas_helper.rb
module CriancasHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/_form.html.erb
<%= form_for @cliente do |f| %>
	<% if @cliente.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@cliente.errors.count, "erro") %>
				impede de salvar o cliente.
			</h2>
			<ul>
				<% @cliente.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :address %>
		<%= f.text_area :address %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', cliente_path(@cliente) %>

app/views/clientes/index.html.erb
<h1> Lista de Clientes </h1>

<table>
	<tr>
		<th>Nome</th>
		<th>Endereço</th>
		<th>Crianças</th>
		<th colspan="3"></th>
	</tr>

	<% @clientes.each do |cliente| %>
			<tr>			
				<td><%= cliente.name %></td>
				<td><%= cliente.address %></td>
				<td>
				<% cliente.criancas.each do |crianca| %>
					<%= crianca.name %>, 
				<% end %>				
				</td>
				<td><%= link_to 'Show', cliente_path(cliente) %></td>
				<td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
				<td><%= link_to 'Destroy', cliente_path(cliente), 
					method: :delete, 
					data:{ confirm: 'Tem certeza que deseja excluir o cadastro do Cliente?'} %></td>
			</tr>
	<% end %>
</table>
</br></br>

<div><%= link_to 'Novo Cliente', new_cliente_path %></div>

<div>
	<%= form_tag clientes_path, method: :get do %>
		<div>
			<label>Busca Cliente:</label>
			<%= text_field_tag :search, params[:search] %><%= submit_tag 'Search' %>
		</div>
	<% end %>
</div>


<br><br><br>
<%= react_component 'Clientes', { data: @clientes } %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Voltar', clientes_path %>

app/views/clientes/show.html.erb
<h1> Cadastro do Cliente </h1>

<p>
	<strong>Nome:</strong>
	<%= @cliente.name %>
</p>

<p>
	<strong>Endereço:</strong>
	<%= @cliente.address %>
</p>

<strong>Emails:</strong>
<table id='email'>
	<tr>
		<th>Email</th>
		<th colspan="4"></th>
	</tr>
	<%= render @cliente.emails %>
</table>

 <br>
<strong>Telefones:</strong>
<table id='fones'>
	<tr>
		<th>DDD</th>
		<th>Telefone</th>
		<th>Tipo</th>
		<th colspan="4"></th>
	</tr>
	<%= render @cliente.telefones %>
</table>

<br>
<strong>Crianças:</strong>
<table id='criancas'>
	<tr>
		<th>Nome</th>
		<th>Mês</th>
		<th>Ano</th>
		<th colspan="4"></th>
	</tr>
	<%= render @cliente.criancas %>
</table>

<br><br>
<h3> Adicionar email:</h3>
<%= render 'emails/form' %>

<br>
<h3> Adicionar telefone:</h3>
<%= render 'telefones/form' %>

<br>
<h3> Adicionar criança:</h3>
<%= render 'criancas/form' %>

<br><br>
<%= link_to 'Editar dados do Cliente', edit_cliente_path(@cliente) %><br>
<%= link_to 'Voltar', clientes_path %>

app/views/criancas/_crianca.html.erb
<tr>
	<td><%= crianca.name %></td>
	<td><%= crianca.mes %></td>
	<td><%= crianca.ano %></td>
	<td><%= link_to 'Remover Criança', [crianca.cliente, crianca],
				method: :delete,
				data: { confirm: 'Tem certeza que deseja remover a criança do cadastro?'} %></td>
</tr>

app/views/criancas/_form.html.erb
<%= form_for([@cliente, @cliente.criancas.build]) do |f| %>

	<p>
		Nome: <%= f.text_field :name %>
	</p>
	<p>		
		Mês: <%= f.select(:mes, ['JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ']) %>

	</p>
	<p>		
		Ano: <%= f.text_field :ano %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cadastro</title>
    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag	'application', 'data-turbolinks-track' => true %>
    <%#= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/telefones/_form.html.erb
<%= form_for([@cliente, @cliente.telefones.build]) do |f| %>
	<p>
		DDD: <%= f.text_field :ddd %>
	</p>
	<p>
		Fone: <%= f.text_field :fone %>
	</p>
	<p>		
		Tipo: <%= f.select(:tipo, ['CELULAR','RESIDENCIAL','COMERCIAL']) %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/telefones/_telefone.html.erb
<tr>
	<td><%= telefone.ddd %></td>
	<td><%= telefone.fone %></td>
	<td><%= telefone.tipo %></td>
	<td><%= link_to 'Remover Telefone', [telefone.cliente, telefone],
			method: :delete,
			data: { confirm: 'Tem certeza que deseja remover o telefone do cadastro?'} %></td>
</tr>

app/views/welcome/index.html.erb
<h1>Cadastro de Clientes</h1>
<p>Escolha uma opção abaixo:</p></br>
<%= link_to 'Lista Clientes', controller: 'clientes' %></br>
<%= link_to 'Adicionar novo cliente', new_cliente_path %>
<%= form_tag clientes_path, method: :get do %>
    <div>
        <label>Busca Cliente:</label>
        <%= text_field_tag :search, params[:search] %><%= submit_tag 'Search' %>
    </div>
<% end %>